global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/recording-rules.yml
  - /etc/prometheus/alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: rabbitmq
    metrics_path: /metrics/per-object
    static_configs:
      - targets: ["rabbitmq:15692"]

  - job_name: shopngo-services-metrics
    metrics_path: /metrics
    static_configs:
      - targets: ["order-service:8080"]
        labels:
          service: order-service
      - targets: ["stock-service:8080"]
        labels:
          service: stock-service
      - targets: ["notification-service:8080"]
        labels:
          service: notification-service

  - job_name: shopngo-health
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets: ["http://order-service:8080/health/live"]
        labels:
          service: order-service
          probe: live
      - targets: ["http://order-service:8080/health/ready"]
        labels:
          service: order-service
          probe: ready
      - targets: ["http://stock-service:8080/health/live"]
        labels:
          service: stock-service
          probe: live
      - targets: ["http://stock-service:8080/health/ready"]
        labels:
          service: stock-service
          probe: ready
      - targets: ["http://notification-service:8080/health/live"]
        labels:
          service: notification-service
          probe: live
      - targets: ["http://notification-service:8080/health/ready"]
        labels:
          service: notification-service
          probe: ready
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
